### ISSUE TITLE
[Roadmap] 0.0.1 Roadmap 

### ISSUE THREAD

**Issue by jackie930** [jackie930/steward-sentiment-anlysis-bot#1]
Functional support list

- [x] Add support for Unbalanced dataset by passing weight list 
- [x] Add support for showing CloudWatch loss while training in SageMaker 
- [x] Add support for multi-gpu training 
- [x] Add support for loss monitoring 
- [x] Add support for incremental training
